# Meta Data for SEO

## Homepage
title = "OpenFOAM Parallelization Workshop"
titleSeparator = "-"
titleAddition = "Parallelization in OpenFOAM for HPC deployment"
description = "A hands-on workshop for OpenFOAM programmers"

## Documentation
# docsVersion = "0.3"

## Open Graph
images = ["opw-logo.png"]
ogLocale = "en_US"
domainTLD = "openfoam-parallelization-workshop.netlify.app"
titleHome = "OpenFOAM parallelization workshop"

## Twitter Cards
twitterSite = "@openfoam-parallelization-workshop"
twitterCreator = ""

## JSON-LD
# schemaType = "Person"
schemaType = "Organization"
schemaName = "OpenFOAM Parallelization Workshop"
schemaAuthor = "Mohammed Elwardi Fadeli"
#schemaAuthorTwitter = "https://twitter.com/henkverlinde"
schemaAuthorLinkedIn = "https://www.linkedin.com/in/elwardi-fadeli/"
schemaAuthorGitHub = "https://github.com/FoamScience"
schemaLocale = "en-US"
schemaLogo = "logo-doks.png"
schemaLogoWidth = 500
schemaLogoHeight = 500
schemaImage = "doks.png"
schemaImageWidth = 500
schemaImageHeight = 500
#schemaTwitter = "https://twitter.com/getdoks"
schemaLinkedIn = "https://www.linkedin.com/company/nhr4ces/"
schemaGitHub = ""
schemaSection = "blog"

## Sitelinks Search Box
siteLinksSearchBox = true

## Chrome Browser
themeColor = "#fff"

# Images
quality = 85
bgColor = "#fff"
landscapePhotoWidths = [900, 800, 700, 600, 500]
portraitPhotoWidths = [800, 700, 600, 500]
lqipWidth = "20x"
smallLimit = "300"

# Images
imageResponsive = true
imageConvertTo = "webp"
imageImageSizes = ["480","720","1080","1280","1600","2048"]
singleSize = false
imageAddClass = "img-fluid lazyload blur-up"

### Image template
defaultImage = "default-image.png" # put in `./assets/images/`
fillImage = "1270x740 Center" # normalize image size

# Footer
footer = "Supported by <a href='https://nhr4ces.de'>NHR4CES</a> - SDL Energy Conversion <br> Cookies are not used to collect anything. <br> Copyright (c) 2022-2023 Mohammed Elwardi Fadeli, based on <a href='https://getdoks.org/'>doks</a> with <a href='https://gohugo.io/'>Hugo</a>"

# Feed
copyRight = "Copyright (c) 2022-2023 Mohammed Elwardi Fadeli"

# Alert
alert = true
alertDismissable = true
# alertText = "Introducing the Doks child theme, several DX + UX updates, and more! <a class=\"alert-link stretched-link\" href=\"https://getdoks.org/blog/doks-v0.2/\" target=\"_blank\" rel=\"noopener\">Check out Doks v0.2</a>"
alertText = "Hands-on sessions will be hosted live. Please register at eveeno.com!"

# Edit Page
# repoHost [Github | Gitea | GitLab | Bitbucket | BitbucketServer ] is used for building the edit link based on git hoster
repoHost = "GitHub"
#repoHost = "Gitea"
docsRepo = "https://github.com/FoamScience"
docsRepoBranch = "master"
docsRepoSubPath = ""
editPage = false
lastMod = true

[sections]
  sectionNav = ["workshop"]

[options]
  lazySizes = true
  clipBoard = true
  instantPage = true
  flexSearch = true
  searchSectionsShow = []
  searchSectionsIndex = []
  darkMode = true
  bootStrapJs = true
  breadCrumb = true
  highLight = true
  kaTex = false
  multilingualMode = false
  docsVersioning = false
  fullWidth = true
  navbarSticky = true
  toTopButton = false
  scrollSpy = false # experimental; needs Bootstrap >= 5.2.0-beta1

[menu]
  [menu.section]
    auto = true
    collapsibleSidebar = true
